services:
  apache:
    profiles: [apache]
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"

  nginx:
    profiles: [nginx]
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:8080"
